name: Build

on: [push]

jobs:

  # -- TESTS ------------------------------------------------------------------
  unit-tests:
    name: Unit-Tests
    runs-on: ubuntu-latest

    steps:
      - name: Harden GitHub Actions Runner
        uses: step-security/harden-runner@8a1ef77ccd7a6d18b009c8cd833b00f49386b657
        with:
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            agent.api.stepsecurity.io:443
            proxy.golang.org:443
            storage.googleapis.com:443
            sum.golang.org:443

      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: "1.19"

      - name: Build the Go app
        run: make go-build
      
      - name: Run the tests
        run: make go-test

  # -- SAST SCAN --------------------------------------------------------------
  code-security:
    name: Code Security
    runs-on: ubuntu-latest
    needs:
      - unit-tests
    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: Harden GitHub Actions Runner
        uses: step-security/harden-runner@8a1ef77ccd7a6d18b009c8cd833b00f49386b657
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            auth.docker.io:443
            docker.io:443
            github.com:443
            nvd.nist.gov:443
            osv-vulnerabilities.storage.googleapis.com:443
            production.cloudflare.docker.com:443
            proxy.golang.org:443
            pypi.org:443
            registry-1.docker.io:443
            storage.googleapis.com:443
            sum.golang.org:443

      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: "1.19"

      - name: Build Go app
        run: make go-build

      - name: Perform Scan
        uses: ShiftLeftSecurity/scan-action@master

        env:
          WORKSPACE: https://github.com/${{ github.repository }}/blob/${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCAN_ANNOTATE_PR: true

      - name: Save the reports
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # v3.1.1
        with:
          name: reports
          path: reports
  
  # -- PRE-RELEASE ------------------------------------------------------------
  pre-release:
    name: Pre-Release
    runs-on: ubuntu-latest
    needs:
      - code-security
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Harden GitHub Actions Runner
        uses: step-security/harden-runner@419f9d6ef954c3c7214dcf0b9babec78755dda8f
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          ref: 'main' # Force checkout of main branch to avoid cache from previous jobs
          persist-credentials: false

      - name: Prepare Release
        uses: cycjimmy/semantic-release-action@071ef4c9640be3700de2aa7f39e8f4038e0269ed # tag=v3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}