name: Code Review

on: [pull_request]

# Declare default permissions as read only.
permissions: read-all

jobs:

  # -- GO LINT ----------------------------------------------------------------
  go-lint:
    name: GO Lint
    runs-on: ubuntu-latest

    steps:
      - name: Harden GitHub Actions Runner
        uses: step-security/harden-runner@eba91136efc2e47cf9832255264a9dcd1fb9defb
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      # Setup Go & Build
      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      # Build the Go app
      - name: Build Go app
        run: make go-build

      # Run staticcheck
      - name: Run Staticcheck
        uses: reviewdog/action-staticcheck@6b0e8bb1967e92767fb04585b17660b67ae07762 # v1.10.2
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          reporter: github-pr-review
          filter_mode: nofilter
          fail_on_error: true

  # -- DOCKER LINT ------------------------------------------------------------
  docker-lint:
    name: Docker Lint
    runs-on: ubuntu-latest

    steps:
      - name: Harden GitHub Actions Runner
        uses: step-security/harden-runner@eba91136efc2e47cf9832255264a9dcd1fb9defb
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Run Hadolint
        uses: reviewdog/action-hadolint@7bd0800b7ce35c6d644cde762174e69f18896973 # v1.35.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          reporter: github-pr-review
