name: Code Review

on: [pull_request]

# Declare default permissions as read only.
permissions: read-all

jobs:

  # -- GO LINT ----------------------------------------------------------------
  go-lint:
    name: GO Lint
    runs-on: ubuntu-latest

    steps:
      - name: Harden GitHub Actions Runner
        uses: step-security/harden-runner@532ef4a868ff5b0fcb05cad9f2aa4f6c81a35bf7
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1

      # Setup Go & Build
      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      # Build the Go app
      - name: Build Go app
        run: make go-build

      # Run staticcheck
      - name: Run Staticcheck
        uses: reviewdog/action-staticcheck@6b0e8bb1967e92767fb04585b17660b67ae07762 # v1.10.2
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          reporter: github-pr-review
          filter_mode: nofilter
          fail_on_error: true

  # -- DOCKER LINT ------------------------------------------------------------
  docker-lint:
    name: Docker Lint
    runs-on: ubuntu-latest

    steps:
      - name: Harden GitHub Actions Runner
        uses: step-security/harden-runner@532ef4a868ff5b0fcb05cad9f2aa4f6c81a35bf7
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1

      - name: Run Hadolint
        uses: reviewdog/action-hadolint@141ffd8d2f0b75e6fc7c87341331985448b62aa4 # v1.34.1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          reporter: github-pr-review
